title: <p align="center"> Jayottam Jadhav </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="/assets/pdf/Jayottam Jadhav CV Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jayottam-jadhav-58975337/">LinkedIn</a> |
  <a href="https://github.com/jayottam">GitHub</a>
  
  <br>   
  Engineer at heart and entrepreneur mind, having decade of experience in building scalable applications using plethora of technologies. 
  <br>
  </p>



theme: jekyll-theme-minimal